version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/app.client'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/app.admin'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/lib.components'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
