client:
  - changed-files:
    - any-glob-to-any-file: 'apps/client/**'

admin:
  - changed-files:
    - any-glob-to-any-file: 'apps/admin/**'

api:
  - changed-files:
    - any-glob-to-any-file: 'services/api/**'

components:
  - changed-files:
    - any-glob-to-any-file: 'packages/lib.components/**'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/*'
      - '**/*.md'
