name: Type Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check all packages
        run: |
          npm run build:components --workspaces --if-present --ignore-scripts
          npm run build:client --workspaces --if-present --ignore-scripts
          npm run build:admin --workspaces --if-present --ignore-scripts
          npm run build:backend --workspaces --if-present --ignore-scripts
          npx tsc --noEmit --skipLibCheck
